version: "3.4"

services:

  laika-example:
    build:
      dockerfile: ./docker/laika-example.dockerfile
      context: ./
    environment:
      DISPLAY: host.docker.internal:0
    ports:
      # Mapping the port to make the Gemini server accessible outside of the container
      - "1965:1965"
    volumes:
      - type: bind
        source: ./erlang
        target: /laika-example
